---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	SourcingExtractor(SourcingExtractor)
	GeographyExtractor(GeographyExtractor)
	ContractExtractor(ContractExtractor)
	SplitterEngine(SplitterEngine)
	SystemClassifierRAG(SystemClassifierRAG)
	QualityValidator(QualityValidator)
	LLMFailRowFixer(LLMFailRowFixer)
	__end__([<p>__end__</p>]):::last
	ContractExtractor --> SplitterEngine;
	GeographyExtractor --> ContractExtractor;
	QualityValidator --> LLMFailRowFixer;
	SourcingExtractor --> GeographyExtractor;
	SplitterEngine --> SystemClassifierRAG;
	SystemClassifierRAG --> QualityValidator;
	__start__ --> SourcingExtractor;
	LLMFailRowFixer --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
